<<<<<<< HEAD
baseurl: "https://beyzakkoyunlu.netlify.app/"
languageCode: en-us
title: A generic grad student website
=======
baseurl: /
languageCode: en-us
title: A Hugo website
>>>>>>> ef42c4bc0c611bb9f30b110ac089e8c56264b46b
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
<<<<<<< HEAD
      url: https://github.com/beyzakkoyunlu
    - name: Twitter
      url: https://twitter.com/beyzakkoyunlu
=======
      url: https://github.com/rstudio/blogdown
    - name: Twitter
      url: https://twitter.com/rstudio
>>>>>>> ef42c4bc0c611bb9f30b110ac089e8c56264b46b
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
